name: kupu
favicon: null
layout_spectrum: 0.9263636060059071
typography_spectrum: 0.4464822458103299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14805132569745183
  lightness: 0.2979450081475079
  saturation: 0.9551016364712268
  rhythmicContrast: 0.4156749190296978
purpose: []
