name: kupu
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5319149
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f0f'
    - '#fef0ed'
    - '#ff2b2f'
    - '#464d67'
    - '#ac8460'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
