layout_spectrum: 0.4957447
favicon: null
name: kupu
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0
  saturation: 0.25
  brandColors:
    - '#0f0f0f'
    - '#fef0ed'
    - '#ff2b2f'
    - '#464d67'
    - '#ac8460'
  lightness: 0.875
  rhythmicContrast: 0.75
typography_spectrum: 0.5319149
